//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademyEntities : DbContext
    {
        public AcademyEntities()
            : base("name=AcademyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

       /* public DbSet GetTableType (string tableName)
        {
            switch (tableName)
            {
                case "Curators":
                    return this.Curators;
                case "Departments":
                    return this.Departments;
                case "Faculties":
                    return this.Faculties;
                case "Groups":
                    return this.Groups;
                case "GroupsCurators":
                    return this.GroupsCurators;
                case "GroupsLectures":
                    return this.GroupsLectures;
                case "Lectures":
                    return this.Lectures;
                case "Subjects":
                    return this.Subjects;
                case "Teachers":
                    return this.Teachers;
            }
            return null;
        }*/
    
        public virtual DbSet<Curators> Curators { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Faculties> Faculties { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupsCurators> GroupsCurators { get; set; }
        public virtual DbSet<GroupsLectures> GroupsLectures { get; set; }
        public virtual DbSet<Lectures> Lectures { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
